System.out.println("                                                                                                                          ");
System.out.println("                                                                                                                          ");
System.out.println("                                                                                                                          ");
System.out.println("                                                                                                                          ");
System.out.println("                                                                                                                          ");
System.out.println("                                                                                                                          ");
System.out.println("                                                                                                                             ");
System.out.println("                                                                                                                          ");
System.out.println("                                            _____________________                                                                        ");
System.out.println("                                           /                     \                                             ");
System.out.println("                                          /                       \                                                           ");
System.out.println("                                         /                         \                                                         ");
System.out.println("                                        /___________________________\                                                                              ");
System.out.println("                                       /\                           /\                                                       ");
System.out.println("                                      /  \                         /  \                                                      ");
System.out.println("                                     /    \                       /    \                                                     ");
System.out.println("                                    /      \                     /      \                                                   ");
System.out.println("                    _______________/        \                   /        \_______________                                   ");
System.out.println("                   /              /          \_________________/          \              \                                     ");
System.out.println("                  /              /           /                 \           \              \                                     ");
System.out.println("                 /              /           /     _________     \           \              \                                    ");
System.out.println("                /______________/           /      |_|_|_|_|      \           \______________\                ");
System.out.println("               /\               \         /       |_|_|_|_|       \         /               /\ ");
System.out.println("              /  \               \       /        |_|_|_|_|        \       /               /  \          ");
System.out.println("             /    \               \     /         |_|_|_|_|         \     /               /    \               ");
System.out.println("            /      \               \   /                             \   /               /      \        ");
System.out.println("           /        \_______________\_/_______________________________\_/_______________/        \       ");
System.out.println("          /         /                                                                   \         \      ");
System.out.println("         /         /     _______                   _______                   _______     \         \     ");
System.out.println("        |\        /      |_|_|_|                   |_|_|_|                   |_|_|_|      \        /|      ");
System.out.println("       _| \      /       |_|_|_|                   |_|_|_|                   |_|_|_|       \      / |_        ");
System.out.println("      / |  \    /        |_|_|_|                   |_|_|_|                   |_|_|_|        \    /  | \       ");
System.out.println("     /  |   \  /                                                                             \  /   |  \       ");
System.out.println("    /   | \  \/_______________________________________________________________________________\/  / |   \      ");
System.out.println("   /    | |\ |                                                                                 | /| |    \           ");
System.out.println("  /_____| \| |      _____       _____         _____       _____         _____       _____      | |/ | ____\          ");
System.out.println(" |\     \  \ |      |_|_|       |_|_|         |_|_|       |_|_|         |_|_|       |_|_|      | /  /     /|   ");
System.out.println(" ||\     \   |      |_|_|       |_|_|         |_|_|       |_|_|         |_|_|       |_|_|      |   /     /||      ");
System.out.println(" || \     \  |                                                                                 |  /     / ||   ");
System.out.println(" || /\     \ |                                                                                 | /     /\ ||      ");
System.out.println(" ||/  \     \|_________________________________________________________________________________|/     /  \||        ");
System.out.println(" ||    \    /                                                                                   \    /    ||       ");
System.out.println(" ||_____\  /                                                                                     \  /_____||       ");
System.out.println(" \|      \/_______________________________________________________________________________________\/      |/           ");
System.out.println("  \      ||  |           |_|_|       |_|_|           ___          |_|_|        |_|_|           |  ||      /          ");
System.out.println("   \     ||\ |           |_|_|       |_|_|          | | |         |_|_|        |_|_|           | /||     /       ");
System.out.println("    \    || \|                                      | | |                                      |/ ||    /             ");
System.out.println("     \   ||  |______________________________________|_|_|______________________________________|  ||   /             ");
System.out.println("      \  || /                                                                                   \ ||  /               ");
System.out.println("       \ ||/                                                                                     \|| /                     ");
System.out.println("        \||_______________________________________________________________________________________||/                        ");
System.out.println("                                                                                                                             ");
System.out.println("                                                                                                                           ");
System.out.println("                                                                                                                          ");